### ISSUE TITLE
Please update to Nextcloud 27 and 28!

### ISSUE THREAD

**Issue by FlattusBlastus** [MarcelRobitaille/nextcloud_google_synchronization#10]
I use this app for my family and friends!

Please update it!

**HUGGLES**

**Comment by lroyb** [comment]
I use this too, but don't want to upgrade to 27 or 28, Until I know it works, either by being updated or enabled as unsupported app

**Comment by lroyb** [comment]
took the plunge, updated to 27.1.2. after upgrade and app updates. enabled the untested app. and it works

**Comment by lroyb** [comment]
took the plunge, updated to 27.1.2. after upgrade and app updates. enabled the untested app. and it works

**Comment by MarcelRobitaille** [comment]
Hi everyone. Sorry I haven't been around. For some reason, even though I own this fork, it was not set up to send me notifications on issues and PRs. Sorry about that! I've signed up now.

Thanks for testing that @lroyb 

I have gotten a lot of requests to update to 28. I will look into it.

**Comment by MarcelRobitaille** [comment]
There is now a release that adds support for up to Nextcloud 29 https://github.com/MarcelRobitaille/nextcloud_google_synchronization/releases/tag/v2.1.0-1
