### ISSUE TITLE
Wrong parameter count Blocking Downway Sync

### ISSUE THREAD

**Issue by geraldurbas** [MarcelRobitaille/nextcloud_google_synchronization#12]
Real Synconisation is not working.

The "Downsync"  task seems broken:

in File  /lib/Controller/GoogleAPIController.php 
Line: 245; a call is made to $this->googleCalendarAPIService->registerSyncCalendar
but with 5 instead of 4 Parameters.

The method  in File /lib/Service/GoogleCalendarAPIService.php  Line 427 
does not use accessToken

After "fixing" that (equal result by adding or removin the param) i got my Downsync.

**Comment by MarcelRobitaille** [comment]
Hi everyone. Sorry I haven't been around. For some reason, even though I own this fork, it was not set up to send me notifications on issues and PRs. Sorry about that! I've signed up now.

@geraldurbas  Could you please let me know:
- The nextcloud version
- The Calendar app version
- The version of this extension

**Comment by geraldurbas** [comment]
Extension: 	1.0.9
Nextcloud: Maybe 27.1.6, or before (cant remember last Update)
Calendar: 4.6.5
>have a look at https://github.com/MarcelRobitaille/nextcloud_google_synchronization/pull/13

Easy fixable; just a missing parameter!

**Comment by MarcelRobitaille** [comment]
Sorry I did not read your issue carefully enough. I copy pasted the same message as I was catching up. 

I am aware of the problem. I'm not sure how this app ever worked. I am working on a new release that will be published this week including that fix

**Comment by geraldurbas** [comment]
no P.
i look out 4 the update & report testytest results;)

**Comment by MarcelRobitaille** [comment]
@geraldurbas I have release the update https://github.com/MarcelRobitaille/nextcloud_google_synchronization/releases/tag/v2.1.0-1
