### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Christophmarczinzik** [MarcelRobitaille/nextcloud_google_synchronization#15]
### Which version of integration_google are you using?

2.1.0-1

### Which version of Nextcloud are you using?

Nextcloud 28.0.3, PHP 8.3, Apache2

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome, Firefox, Edge....

### Describe the Bug

I have 300 errors in my Log every day. I tested an New install of Nextcloud and the same error. In the new and old Nexcloud install the same Error every day. 
Nextcloud 28.0.3
PHP 8.3
Apache2
Ubuntu 22.04 (VM in Proxmox)

`Undefined property: OCA\\Google\\Service\\GoogleCalendarAPIService::$appName at /var/www/nextcloud/apps/google_synchronization/lib/Service/GoogleCalendarAPIService.php#177`

### Expected Behavior

`Undefined property: OCA\\Google\\Service\\GoogleCalendarAPIService::$appName at /var/www/nextcloud/apps/google_synchronization/lib/Service/GoogleCalendarAPIService.php#177`

### To Reproduce

`Undefined property: OCA\\Google\\Service\\GoogleCalendarAPIService::$appName at /var/www/nextcloud/apps/google_synchronization/lib/Service/GoogleCalendarAPIService.php#177`

![Nextcloud_Error](https://github.com/MarcelRobitaille/nextcloud_google_synchronization/assets/75455219/e9f83a0f-e1e7-40b5-924b-cc3781f900e0)

**Comment by MarcelRobitaille** [comment]
Hi @Christophmarczinzik thanks for opening this issue. Could you please try version 2.1.0-2-nightly? I think I may have found the issue. I'm still not sure why this is happening for you and not me or anyone else.

**Comment by Christophmarczinzik** [comment]
Hi @MarcelRobitaille 
Yes I think that helped, I updated 15 minutes ago and there were no new errors. I'll look at the log files again in 1-2 hours

thank u :)

**Comment by MarcelRobitaille** [comment]
That's great news. I'll close this for now. Feel free to reopen it if it pops up again.
