### ISSUE TITLE
Please update the Nextcloud Store for NC28/29 compatibility

### ISSUE THREAD

**Issue by FlattusBlastus** [MarcelRobitaille/nextcloud_google_synchronization#16]
### Which version of integration_google are you using?

None

### Which version of Nextcloud are you using?

28.0.3

### Describe the Bug

I have used this version and prefer it over the mere Google Integration app.

### Expected Behavior

Able to install in the latest Nextcloud

### To Reproduce

View the NC App Store

**Comment by MarcelRobitaille** [comment]
Hi. I'm sorry, I don't understand. This app should be compatible with nextcloud 28 and 29.

**Comment by FlattusBlastus** [comment]
[image: image.png]

Version 1.0.9 shows up from the store.

**Comment by MarcelRobitaille** [comment]
Version 2.1.0-1 is released: https://apps.nextcloud.com/apps/google_synchronization

It is compatible with Nextcloud version 28 and 29. I don't think this is a problem on my end.

By the way, I don't see your image, only [image: image.png]

**Comment by FlattusBlastus** [comment]
I am running the develop build of AIO. Will that make a difference?

How can I install this manually?

**Comment by FlattusBlastus** [comment]
I was able to install the unstable version.

**Comment by MarcelRobitaille** [comment]
Hi @FlattusBlastus. Does that mean this issue is resolved? I'm not sure why you cannot install the version from within Nextcloud. As my app shows up in the store, I don't think the problem is on my side.

**Comment by ibaraki-douji** [comment]
For me it's working like a charm !

The only thing is that the version is not installable with the UI cuz it's unstable. (or i didn't find the option to enable it on NC28)

So you can install with the CLI
`./occ app:install --allow-unstable google_synchronization`

And if wrong UID when running the command above
`sudo -u "#33" ./occ app:install --allow-unstable google_synchronization`

**Comment by MarcelRobitaille** [comment]
Which version can you not install from the UI? 2.1.0-1 is stable and installable through the UI. It is compatible with NC 28 and 29.

Thanks for the occ tip. I didn't know about that.

**Comment by FlattusBlastus** [comment]
This..... In the UI store, 1.09 was offered.

________________________________

**Comment by MarcelRobitaille** [comment]
I think I figured out the problem. I was adding a `-1` after the semver version number to show the version of the fork upstream and then how many versions I made on top of the fork upstream. I just release 2.1.1 and now it shows up in NC.

**Comment by ibaraki-douji** [comment]
Yep i got the update notification for it in the UI, thanks ;)
