### ISSUE TITLE
Requesting feature please: reverse sync - I want Nextcloud calendar to be my primary calendar, and then sync my Nextcloud calendar to Google

### ISSUE THREAD

**Issue by Majestic7979** [MarcelRobitaille/nextcloud_google_synchronization#25]
### Describe the feature you'd like to request

I would like to create and manage all my events in Nextcloud calendar, and then sync them to Google Calendar, so that my smartwatch and Google Assistant can pull the data and offer me reminders, etc.

Currently everyone is focusing on syncing Google data into Nextcloud, I want to do the reverse, push my Nextcloud calendar to Google. Is this possible, can you do it please?

### Describe the solution you'd like

Push data from Nextcloud to Google, basically the reversed process of what you have now.

### Describe alternatives you've considered

No alternative seems to exist.

**Comment by MarcelRobitaille** [comment]
I do not want to support this. You are welcome to fork, but I suspect that it would be an almost total rewrite (a big part of why I don't want to support it).

Is your nextcloud instance accessible to the internet? If yes, you can just create a share link for your NC calendar and import it into google calendar.

**Comment by Majestic7979** [comment]
No problem, thanks.

I tried to use the CalDAV link but Google Calendar is not syncing it. Yes, I have a fully exposed instance with A+ security rating.

**Comment by MarcelRobitaille** [comment]
Thanks for understanding. I think that should be possible.

Maybe this helps you: https://help.nextcloud.com/t/sync-share-google-calendar-nextcloud-calendar/114131

**Comment by Majestic7979** [comment]
> Thanks for understanding. I think that should be possible.
> 
> Maybe this helps you: https://help.nextcloud.com/t/sync-share-google-calendar-nextcloud-calendar/114131

Oh of course, no problem, thanks for even replying, and even more for going through search to try to help, very kind of you! I found the same thread and tried to follow instructions for that script but unfortunately it only works for Google Workspace accounts, not free Gmail ones :( Anyway you've been great, thanks a lot :)

**Comment by Ullulaki** [comment]
@Majestic7979 Normally that should work with CalDAV. Maybe it's the app? Try to use [DAVx5](https://www.davx5.com/) or the app CalenGoo. I use it and have all my calendars (google paired with alexa + nextcloud) there and it's working without any problems.
