### ISSUE TITLE
Error on clicking Sync Calendar

### ISSUE THREAD

**Issue by SDS1337** [MarcelRobitaille/nextcloud_google_synchronization#6]
Nextcloud version 25.0.5. Plugin version 1.0.9

When clicking Sync Calendar, this error pops up, taking up the entire screen.
Image posted in the end.
Content of error without the newlines:
```
Failed to register background job:
Nextcloud
<div id="nojavascript">
<div>
This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page. </div>
</div>
```

What's weird is, JavaScript is not disabled. It also shows JavaScript as enabled upon visiting enable-javascript.com.

I've tried doing it on Vivaldi Desktop, MS Edge Desktop, and Vivaldi Android. Getting the same error every time. 

Import Calendar works as expected, but sync does not. I've tried disabling extensions in my browser to see if they might be interfering but no change.

![image](https://user-images.githubusercontent.com/77174743/227752212-fc1c4db6-7847-438f-988b-de1bd7faba8f.png)

**Comment by tlpwka** [comment]
I have the same issue.
Nextcloud 24.0.11
Plugin version 1.0.9

**Comment by DanielEdlich** [comment]
Same issue in Nextcloud 26.0.0
I got the following error: 
```
ReflectionException: Method OCA\Google\Controller\GoogleAPIController::registerSyncCalendar() does not exist
/var/www/html/lib/private/AppFramework/Utility/ControllerMethodReflector.php - line 51:

ReflectionMethod->__construct([ "OCA\\Goog ... "], "registerSyncCalendar")

/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 127:

OC\AppFramework\Utility\ControllerMethodReflector->reflect([ "OCA\\Goog ... "], "registerSyncCalendar")

/var/www/html/lib/private/AppFramework/App.php - line 183:

OC\AppFramework\Http\Dispatcher->dispatch([ "OCA\\Goog ... "], "registerSyncCalendar")

/var/www/html/lib/private/Route/Router.php - line 315:

OC\AppFramework\App::main("OCA\\Google ... r", "registerSyncCalendar", [ "OC\\AppFr ... "], [ "google_sy ... "])

/var/www/html/lib/base.php - line 1055:

OC\Route\Router->match("/apps/googl ... r")

/var/www/html/index.php - line 36:

OC::handleRequest()
```

**Comment by AzureInformatique** [comment]
Same error on Nextcloud 26.0.0

**Comment by Happyfeet01** [comment]
Same here.

**Comment by haw-haw** [comment]
same error

**Comment by spankyboy** [comment]
A little late to the conversation...

Running nextcloud 24.0.12, Sync version 1.0.9.

Same issue, but when I installed and enabled Google Integration (1.0.9), then enable synchronization, it all worked.

Note that integration and sync use different redirects.  Make sure you list both in the google oauth client credentials.

Hope this helps anybody still banging their head....

**Comment by lroyb** [comment]
If you get the javascript error. I also had this, but after a couple of hour, I finally today I sorted it.

if you read the markdown file, it says that it is a fork of the 'google intergration' app. Most importantly it says that ' it should not be used as well as'. So, I disabled the google intergration app, leaving the google Synchronization app enabled. and it worked first try afterward.

**Comment by SDS1337** [comment]
> If you get the javascript error. I also had this, but after a couple of hour, I finally today sorted it.
> 
> if you read the markdown file, it says that it is a fork of the 'google intergration' app. Most importantly it says that ' it should not be used as well as'. So, I disabled the google intergration app, leaving the google Synchronization app enabled. and it worked first try afterward.

Oh my, after having given up on this for so long, such a simple fix 😅.

Disabling the other Google Integration app made this work. Makes sense how it would throw an error since its a fork.
