### ISSUE TITLE
Google Calender Sync Job is registered with wrong argument

### ISSUE THREAD

**Issue by zwiefelp** [MarcelRobitaille/nextcloud_google_synchronization#7]
https://github.com/MarcelRobitaille/nextcloud_google_synchronization/blob/9cbc79b19c3e53e95b1edd6b137e914985524863/lib/Controller/GoogleAPIController.php#L249

Method registerSyncCalender is called with wrong number of argumnents. 
This results in a none working google calender sync background-job. (Misleading Error in Response from google: Missing API-Key...)

First argument (accessToken) needs to be deleted from the call:
$result = $this->googleCalendarAPIService->registerSyncCalendar($this->userId, $calId, $calName, $color);

**Comment by MarcelRobitaille** [comment]
Hi everyone. Sorry I haven't been around. For some reason, even though I own this fork, it was not set up to send me notifications on issues and PRs. Sorry about that! I've signed up now.

@zwiefelp  Could you please let me know:
- The nextcloud version
- The Calendar app version
- The version of this extension

**Comment by MarcelRobitaille** [comment]
This is fixed in [the latest release](https://github.com/MarcelRobitaille/nextcloud_google_synchronization/releases/tag/v2.1.0-1)
